### ISSUE TITLE
S22 wrong coordinates for sacrifice event

### ISSUE THREAD

**Issue by Konrad22** [knyghtmare/The_Eight_of_Cembulad#21]
If I read the intention of the code right, the prisoners are to be sacrificed if you walked past the dungeon and pushed on.
BUT.
If you step on 9,30 or 10,30, you trigger the sacrifice immediatly, about 40 turns before you have can reach the prisoners.
So, just adjust the coordinates I guess.

**Comment by cooljeanius** [comment]
fixed by #16

**Comment by cooljeanius** [comment]
oh looks like I can't close this one myself; @knyghtmare can you do so?
