### ISSUE TITLE
Convert `^Uf` to `^Tf`

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/The_Eight_of_Cembulad#34]
If only they actually provided this in wmllint...sigh...

But VSCode and mass-search-and-replace to the rescue (as always)

**Comment by cooljeanius** [comment]
> If only they actually provided this in wmllint...sigh...

cross-referencing against your PR wesnoth/wesnoth#7206, which would have done so...

**Comment by cooljeanius** [comment]
> > > If only they actually provided this in wmllint...sigh...
> > 
> > 
> > cross-referencing against your PR [wesnoth/wesnoth#7206](https://github.com/wesnoth/wesnoth/pull/7206), which would have done so...
> 
> Leave it be. Those devs too obstinate to see reason these days and we the UMC authors must suffer through due to their actions of irresponsibility

I know, just ["building the web"](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking) so that if someone comes across this wondering why it's not already done, they can have a link to find out...

**Comment by knyghtmare** [comment]
It's not done cause this is low priority for me. Since my RL objectives come first and then Wesnoth so, been really busy lately
