### ISSUE TITLE
S07, Pollur: it doesn't make any sense for the orcs to free the dwarves

### ISSUE THREAD

**Issue by cooljeanius** [knyghtmare/The_Eight_of_Cembulad#6]
Right now in S07 there's a `moveto` event that causes the dwarves to be freed, except the problem is that the orcs can trigger it, which doesn't make any sense. The orcs were the ones imprisoning the dwarves in the first place, so why would they free them just so they can help you defeat them? Should there maybe be a `side=1` added to the criteria that triggers the event?

**Comment by knyghtmare** [comment]
Maybe. I just skimmed that scenario myself. I think the intention was to make it look like the dwarves ambushed the orcs?

**Comment by cooljeanius** [comment]
ok I'll add `side=1` to the filter, then

**Comment by cooljeanius** [comment]
fixed by #16
